@host = https://ag.luminbe.cn
@token = 500a2467-8119-49a8-bfda-1ce5992b4d43


### 获取公共配置信息
GET {{host}}/api/index/getConfig


### 获取验证码
POST {{host}}/api/user/getCaptcha
Content-Type: application/json

{
    "type": "register"
}

### 用户注册
POST {{host}}/api/user/register
Content-Type: application/x-www-form-urlencoded

username=testuser4
&password=aa123123
&email=test@example.com
&mobile=13800138000
&code=123456
&captcha=123456
&invitation_code=0VG7WB


### 用户登录
POST {{host}}/api/user/login
Content-Type: application/x-www-form-urlencoded

username=testuser
&password=aa123123
&captcha=123456

### 获取用户信息
GET {{host}}/api/user/getUserInfo
Content-Type: application/json
token: {{token}}


### 更新用户信息
POST {{host}}/api/user/setUserInfo
Content-Type: application/json
token: {{token}}

{
    "nickname": "测试用户",
    "mobile": "13800138000",
    "email": "test@test.com"
}

### 获取文章列表
GET {{host}}/api/index/article_list?type=events
Content-Type: application/json


### 获取trc20充值地址
POST {{host}}/api/pay/getTrc20Address
Content-Type: application/json
Token: {{token}}

{
}

### trc20充值回调
POST {{host}}/api/pay/trc20Callback
Content-Type: application/json

{
    "order_id": "xxx",
    "user_id": "11",
    "value": "999",
    "signature": "xxx" // md5(order_id + user_id + value + token)
}