@host = https://ag.luminbe.cn
@token = 91e1f90d-35a1-48a2-9f97-a884d1940448


GET {{host}}/api/index/test

### 获取公共配置信息
GET {{host}}/api/index/getConfig


### 获取验证码
POST {{host}}/api/user/getCaptcha
Content-Type: application/json

{
    "type": "register"
}

### 用户注册
POST {{host}}/api/user/register
Content-Type: application/x-www-form-urlencoded

username=testuser4
&password=aa123123
&email=test@example.com
&mobile=13800138000
&code=123456
&captcha=123456
&invitation_code=0VG7WB


### 用户登录
POST {{host}}/api/user/login
Content-Type: application/x-www-form-urlencoded

username=testuser
&password=aa123123
&captcha=123456

### 获取用户信息
GET {{host}}/api/user/getUserInfo
Content-Type: application/json
token: {{token}}


### 更新用户信息
POST {{host}}/api/user/setUserInfo
Content-Type: application/json
token: {{token}}

{
    "nickname": "测试用户",
    "mobile": "13800138000",
    "email": "test@test.com"
}

### 获取文章列表
GET {{host}}/api/index/article_list?type=events
Content-Type: application/json

### 获取文章详情
GET {{host}}/api/index/article_detail?id=1


### 获取trc20充值地址
POST {{host}}/api/pay/getTrc20Address
Content-Type: application/json
Token: {{token}}


### trc20充值回调
POST {{host}}/api/pay/trc20Callback
Content-Type: application/json

{
    "order_id": "xxx1",
    "user_id": "2",
    "value": "9",
    "signature": "1b6eb958ed744194afcec4e5219fb61c"
}

### 获取游戏平台列表
GET {{host}}/api/games/getPlatTypeList

### 获取游戏列表
GET {{host}}/api/games/getGameList

### 获取客服列表
GET {{host}}/api/index/get_kefu_list
Token: {{token}}

### 获取支付渠道列表
GET {{host}}/api/index/get_bank_list


### 用户提交充值
POST {{host}}/api/user/recharge
Content-Type: application/json
Token: {{token}}

{
    "amount": "9999.00",
    "bank_id": "11",
    "transaction_image": "/path/xxx.jpg"
}


### 用户提交提现
POST {{host}}/api/user/withdraw
Content-Type: application/json
Token: {{token}}

{
    "amount": "9.00",
    "bank_id": "11"
}


### 用户实名
POST {{host}}/api/user/realname
Content-Type: application/json
Token: {{token}}

{
    "real_name": "张三",
    "id_card_number": "22",
    "id_card_image1": "",
    "id_card_image2": "2"
}

### 交易记录
GET {{host}}/api/user/monery_log?type=withdraw&timeRange=today
Token: 232b735b-b2bb-42dd-a2c8-cc4cd66832bc

### 获取用户充值总额
GET {{host}}/api/user/get_recharge_sum
Token: {{token}}

###
GET {{host}}/api/Promotion/updateSubAccountIsAgent
Token: {{token}}

{
    "uid": "33",
    "isAgent": "1"
}

###
GET {{host}}/api/promotion/subWithdrawList
Token: {{token}}